site_name: 深入理解计算机系统
theme: readthedocs
# Page tree
nav:
  - 第 0 章 &nbsp; 前言:
        # [icon: material/book-open-outline]
    - 0/index.md
    - 0.1 &nbsp; 关于作者: 0/0.1.md
  - 第 1 章 &nbsp; 计算机系统漫游:
    # [icon: material/book-open-outline]
    - 1/index.md
    - 1.1 &nbsp; 信息就是位+上下文: 1/1.1.md
    - 1.2 &nbsp; 程序被其他程序翻译成不同的格式: 1/1.2.md
    - 1.3 &nbsp; 了解编译系统如何工作是大有益处的: 1/1.3.md
    - 1.4 &nbsp; 处理器读并解释储存在内存中的指令: 1/1.4.md
    - 1.5 &nbsp; 高速缓存至关重要: 1/1.5.md
    - 1.6 &nbsp; 存储设备形成层次结构: 1/1.6.md
    - 1.7 &nbsp; 操作系统管理硬件: 1/1.7.md
    - 1.8 &nbsp; 系统之间利用网络通信: 1/1.8.md
    - 1.9 &nbsp; 重要主题: 1/1.9.md
    - 1.10 &nbsp; 小结: 1/1.10.md
  - 第 2 章 &nbsp; 信息的表示与处理:
    # [icon: material/book-open-outline]
    - 2/index.md
    - 2.1 &nbsp; 信息存储: 2/index.md
    - 2.2 &nbsp; 整数表示: 2/index.md
    - 2.3 &nbsp; 整数运算: 2/index.md
    - 2.4 &nbsp; 浮点数: 2/index.md
    - 2.5 &nbsp; 小结: 2/index.md
